# Generated by Django 5.0.6 on 2024-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertaxi',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ordertaxi',
            name='longitude',
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
