# Generated by Django 5.0.6 on 2024-07-07 14:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ordertaxi_latitude_remove_ordertaxi_longitude_and_more'),
        ('user', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertaxi',
            name='progress',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='taxi_take',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_take_order_taxi', to='user.user', verbose_name='taxi_take'),
        ),
        migrations.AlterField(
            model_name='ordertaxi',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ordertaxi',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaxi',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_taxi', to='user.user', verbose_name='user'),
        ),
    ]
