# Generated by Django 5.0.6 on 2024-07-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ordertaxi_progress_ordertaxi_taxi_take_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertaxi',
            name='taxi_take',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertaxi',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
