# Generated by Django 5.0.6 on 2024-07-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ordertaxi_taxi_take_alter_ordertaxi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertaxi',
            name='user',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
