# Generated by Django 5.0.6 on 2024-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ordertaxi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertaxi',
            name='payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordertaxi',
            name='tarif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
