# Generated by Django 5.0.6 on 2024-07-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ordertaxi_payment_ordertaxi_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco', models.IntegerField()),
                ('comfort', models.IntegerField()),
                ('business', models.IntegerField()),
            ],
        ),
    ]
