# Generated by Django 5.0.6 on 2024-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
