# Generated by Django 5.0.6 on 2024-07-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='../media/avatar/default.png', upload_to='avatar'),
        ),
    ]
