# Generated by Django 5.0.6 on 2024-07-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ordertaxi_taxi_take_alter_ordertaxi_user'),
        ('user', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_order_progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_order_progress', to='main.ordertaxi', verbose_name='is_order_progress'),
        ),
    ]
