# Generated by Django 5.0.6 on 2024-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_orders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='money_taxi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
