# Generated by Django 5.0.6 on 2024-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='money_taxi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
