# Generated by Django 5.0.6 on 2024-07-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_transactions_user_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='types',
            field=models.BooleanField(null=True),
        ),
    ]
