# Generated by Django 5.0.6 on 2024-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_transactions_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transactions',
            field=models.ManyToManyField(to='user.transactions', verbose_name='transactions'),
        ),
    ]
