# Generated by Django 5.0.6 on 2024-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='user.transactions', verbose_name='transactions'),
        ),
    ]
