# Generated by Django 5.0.6 on 2024-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sound_order',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='sound_taxi',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
