# Generated by Django 5.0.6 on 2024-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sound_order',
            field=models.CharField(default='../media/taxi/order.mp', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sound_taxi',
            field=models.CharField(default='../media/taxi/order.mp', max_length=50),
        ),
    ]
