# Generated by Django 5.0.6 on 2024-07-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_job',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='taxi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
