# Generated by Django 5.0.6 on 2024-07-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_is_job_alter_user_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='../media/avatar/default.png', null=True, upload_to='avatar'),
        ),
    ]
