# Generated by Django 5.0.6 on 2024-07-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_discont'),
        ('user', '0021_alter_user_sound_order_alter_user_sound_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_order_progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_order_progress', to='main.ordertaxi', verbose_name='is_order_progress'),
        ),
    ]
